using Xunit;
using RomanNumerals;
using Romanizer;

namespace RomanNumerals.Tests
{
    public class NumeralsTests
    {
        [Theory]
        [InlineData(1, "I")]
        [InlineData(2, "II")]
        [InlineData(3, "III")]
        [InlineData(4, "IV")]
        [InlineData(5, "V")]
        [InlineData(6, "VI")]
        [InlineData(7, "VII")]
        [InlineData(8, "VIII")]
        [InlineData(9, "IX")]
        [InlineData(10, "X")]
        [InlineData(11, "XI")]
        [InlineData(12, "XII")]
        [InlineData(13, "XIII")]
        [InlineData(14, "XIV")]
        [InlineData(21, "XXI")]
        [InlineData(22, "XXII")]
        [InlineData(23, "XXIII")]
        [InlineData(26, "XXVI")]
        [InlineData(27, "XXVII")]
        [InlineData(50, "L")]
        [InlineData(83, "LXXXIII")]
        [InlineData(84, "LXXXIV")]
        [InlineData(89, "LXXXIX")]
        [InlineData(90, "XC")]
        [InlineData(91, "XCI")]
        [InlineData(92, "XCII")]
        [InlineData(100, "C")]
        [InlineData(101, "CI")]
        [InlineData(110, "CX")]
        [InlineData(140, "CXL")]
        [InlineData(144, "CXLIV")]
        [InlineData(149, "CXLIX")]
        [InlineData(150, "CL")]
        [InlineData(199, "CXCIX")]
        [InlineData(212, "CCXII")]
        [InlineData(353, "CCCLIII")]
        [InlineData(404, "CDIV")]
        [InlineData(634, "DCXXXIV")]
        [InlineData(749, "DCCXLIX")]
        [InlineData(820, "DCCCXX")]
        [InlineData(846, "DCCCXLVI")]
        [InlineData(927, "CMXXVII")]
        [InlineData(1000, "M")]
        [InlineData(1348, "MCCCXLVIII")]
        [InlineData(1978, "MCMLXXVIII")]
        [InlineData(2017, "MMXVII")]
        [InlineData(3159, "MMMCLIX")]
        [InlineData(4824, "MMMMDCCCXXIV")]
        [InlineData(6943, "UMCMXLIII")]
        [InlineData(9432, "UMMMMCDXXXII")]
        [InlineData(9999, "UMMMMCMXCIX")]
        public void RomanizeTest(int arabic, string roman)
        {
            Assert.Equal(roman, Numerals.Romanize(arabic));
        }
        [Theory]
        [InlineData("I", 1)]
        [InlineData("II", 2)]
        [InlineData("III", 3)]
        [InlineData("IV", 4)]
        [InlineData("V", 5)]
        [InlineData("VI", 6)]
        [InlineData("VII", 7)]
        [InlineData("VIII", 8)]
        [InlineData("IX", 9)]
        [InlineData("X", 10)]
        [InlineData("XIV", 14)]
        [InlineData("XXVI", 26)]
        [InlineData("XLIV", 44)]
        [InlineData("LXVIII", 68)]
        [InlineData("LXXIX", 79)]
        [InlineData("LXXXVIII", 88)]
        [InlineData("XCIV", 94)]
        [InlineData("XCIX", 99)]
        [InlineData("C", 100)]
        [InlineData("CCXII", 212)]
        [InlineData("CCCLIII", 353)]
        [InlineData("CDIV", 404)]
        [InlineData("DCXXXIV", 634)]
        [InlineData("DCCXLIX", 749)]
        [InlineData("DCCCXX", 820)]
        [InlineData("DCCCXLVI", 846)]
        [InlineData("CMXXVII", 927)]
        [InlineData("M", 1000)]
        [InlineData("MCCCXLVIII", 1348)]
        [InlineData("MCMLXXVIII", 1978)]
        [InlineData("MMXVII", 2017)]
        [InlineData("MMMCLIX", 3159)]
        [InlineData("MMMMDCCCXXIV", 4824)]
        [InlineData("UMCMXLIII", 6943)]
        [InlineData("UMMMMCDXXXII", 9432)]
        [InlineData("UMMMMCMXCIX", 9999)]
        public void NumerizeTest(string roman, int arabic)
        {
            Assert.Equal(arabic, Numerals.Deromanize(roman));
        }

    }
}